### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by cemo** [phax/ph-xsds#2]
Can you please cut a release with latest changes. We need jakarta support since it causes some exceptions with your latest schematron library.

**Comment by phax** [comment]
Release 3.0.0 is out :)

**Comment by cemo** [comment]
Common project too please :)

**Comment by phax** [comment]
Working myself through the components - give me some time :)
What "Commons" project are you exactly referring to?

**Comment by cemo** [comment]
I had used 11.0.0 version of https://github.com/phax/ph-commons project but it had missing one method.

com.helger.xml.XMLHelper#pathToNodeBuilder seems missing in v11.0.0 and I build on my box today it. After it https://github.com/phax/ph-schematron was successfully built. There were some also test errors but skipped them.

**Comment by cemo** [comment]
I will check again, please discard my comment for a while.

**Comment by cemo** [comment]
I opened an issue on https://github.com/phax/ph-commons 

thanks.

**Comment by phax** [comment]
You are right - that was some fix after 10.2.0 which I cherry-picked afterwards. Will make a release, but let me see if there is something else that needs to be changed

**Comment by cemo** [comment]
Thank you. I will be waiting.

**Comment by phax** [comment]
ph-schematron main branch should contain a working version, depending on the ph-commons 11.0.1-SNAPSHOT version. Please confirm

**Comment by cemo** [comment]
ph-commons  has a failing test.  `EJavaVersionTest.testBasic:47` is failing. Skipping tests lets a successful build. Schematron is built successfully with it.

**Comment by phax** [comment]
Ah okay. Are you running Java 18?

**Comment by cemo** [comment]
Yes, I am running on jdk18.
